INSERT INTO curso (curso, nivel_idnivel) VALUES ('Ensino Fundamental (1º grau)', 1);

INSERT INTO curso (curso, nivel_idnivel) VALUES ('Ensino Médio (2º Grau)', 3);

INSERT INTO curso (curso, nivel_idnivel) VALUES ("3D Studio Max", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Acordeon", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("ActionScript MX", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administrativo", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Aeromoça", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agente de turismo", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Artesanato em madeira", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Artes Plásticas", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Assesoria fiscal e tributária", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("ATP Poser 4", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Autocad", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Auxiliar clínica veterinária", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Auxiliar de enfermagem", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Auxiliar de jardim de infância", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Auxiliar de odontologia", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Avaliação de empresas", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cabeleireiro", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Carpintaria", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cenografia", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cobranças por telefone", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Colorimetria aplicada", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Construção predial", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Consultor em segurança Microsoft 2003", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade analítica", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade básica", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade de custos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade geral", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade para executivos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade para servidores", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade pública", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade tributária", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Controle de gestão", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Corte e costura", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Costura em couro", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Criação/gestão de cursos de e-learning", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Culinária", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Curso de língua inglesa", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Curso de línguas estrangeiras", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dança", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Decoração", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho 3Dstudio Max-2003", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho de moda", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho em quadrinhos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho gráfico", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenvolvimento do poder mental", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Design de interiores", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dietética e nutrição", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito comercial", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dreamweaver MX", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação meio-ambiental", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("EJB", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletricista", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletrônica e micro-eletrônica", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Encanador", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Energia solar", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Especialização em audiovisuais", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Especialização em Comércio eletrônico", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Especialização em Contabilidade Gerencial", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Especialização em desenho em movimento", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Especialização em direção comercial e marketing", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Especialização em direito de novas tecnologias", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Especialização em prótese dentária", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estética", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fireworks MX", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fiscalização de operações financeiras", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Flash MX", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fotografia", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão atuarial e financeira", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão de contas", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão de tesouraria", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão em eventos culturais e desportivos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão financeira de pequenas empresas", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão meio-ambiental", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Guitarra", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Imposto de renda", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Impostos de produtos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Informática musical", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Iniciação à música", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Instalação/manutenção de PC's", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Instalador de gás", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Introdução ao Windows, Word e Internet", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("J2EE", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("JAVA 2003 Professional", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Locução e sonoplastia", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Manutenção de ar condicionado", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Master Web", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mecânico de motos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mecânico do automóvel", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Modos de pagamentos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Montagem de cinema e produção TV", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Motores a diesel", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("MS Project", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Normas internacionais de contabilidade", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Oficina/chapista", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedreiro", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Photoshop 6.0", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("PHP e MySQL", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Piano", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pigmentos e corantes", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pintura", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Planejamento fiscal internacional", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção multimídia", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Projetista mecânico", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Proteção Civil", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Recepcionista/Telefonista", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Roteiro de cinema e TV", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Segurança e direito do trabalho", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Serralheiro", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Sistemas micro-informáticos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Soldador", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Supervisor de obras", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Teatro e espaço cênico", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Teclado", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Técnico de alimentos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Técnico em plásticos", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Técnico em tratamento de águas", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Técnico meio-ambiente", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Telemarketing", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tradutor / Intérprete", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tunning", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Vigilante de segurança", 2);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("XML", 2);

INSERT INTO curso (curso, nivel_idnivel) VALUES ("Açúcar e álcool", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Aeroportuário ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agenciamento de viagem", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agricultura", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agrimensura ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agroecologia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agroindústria", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agronegócio", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agropecuária", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Alimentos", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Análises clínicas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Análises químicas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Apicultura ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Aquicultura", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arte circense", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arte dramática", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Artesanato ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Artes gráficas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Artes visuais", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Atividades físicas e desportivas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Automação industrial", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biblioteconomia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Calçados ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Canto", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Celulose e papel ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cerâmica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Citopatologia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comércio ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comércio exterior", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Composição e arranjo", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação visual", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Confeitaria ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Conservação e restauro", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Construção naval", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Contabilidade", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Controle ambiental", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cooperativismo ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cozinha", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Curtimento", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dança", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Departamento pessoal", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho de construção civil", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Design de embalangens", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Design de interiores", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Design de joias", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Design de móveis", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Design gráfico", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Documentação musical", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Edificações", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletroeletrônica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletromecânica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletrônica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletrotécnica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Enfermagem", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Equipamentos biomédicos", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estética", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estradas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eventos", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fabricação de instrumentos musicais", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fabricação mecânica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Farmácia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Finanças", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Florestas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fotografia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Geodésia e cartografia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Geologia ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Geoprocessamento", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gerência em saúde", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gráfica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Guia de turismo", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Hidrologia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Hospedagem", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Imagem pessoal", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Imobilizações ortopédicas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Impressão gráfica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Impressão offset ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Industrial", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Informática", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Informática para internet", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Infraestrutura escolar", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Instrumentador cirúrgico", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Instrumento musical", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Lazer", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Logística", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Magistério", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Manutenção automotiva", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Manutenção de aeronaves", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Manutenção e suporte em informática", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Marketing", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Massoterapia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("ecânica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mecatrônica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Meio ambiente", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Metalurgia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Meteorologia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mineração", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Modelagem do vestuário", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Móveis", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Multimídia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Nutrição e dietética", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Óptica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Paisagismo", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Panificação ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Petróleo e gás", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Petroquímica", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Plásticos", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Portos ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pré-impressão", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Previdência social", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Processamento de pescado", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção de áudio e vídeo", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção de moda", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Programação de jogos digitais", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Prótese dentária", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Publicidade", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Qualidade", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Química", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Rádio e televisão", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Radiologia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Recursos humanos", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Recursos minerais ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Recursos pesqueiros ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Redes de computadores", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Refrigeração e climatização", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Regência", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Registros e informações em saúde", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Saneamento ", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Saúde", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Saúde bucal", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Secretariado", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Secretaria escolar", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Segurança do trabalho", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Serviços de condomínio", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Serviços de restaurante e bar", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Serviços públicos", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Sistemas a gás", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Sistemas de comutação", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Sistemas de transmissão", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tabela de convergência", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tecelagem", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Telecomunicações", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tradutor e intérprete", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Trânsito", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Transporte de cargas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Transporte ferroviário", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Transporte rodoviário", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Transportes", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Vendas", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Vestuário", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Veterinária", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Vigilância em saúde", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Viticultura e enologia", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Web design", 4);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Zootecnia", 4);

INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agrimensura", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agroecologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agroindústria", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agronegócio", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agronomia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Análise e desenvolvimento de sistemas", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Antropologia social e cultural", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Aquicultura", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arqueologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arquitetura e urbanismo", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arquivologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Automação industrial", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biblioteconomia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biocombustíveis", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biomedicina", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Bioquímica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cafeicultura", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências ambientais", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências atuariais e financeiras", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências contábeis", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências da computação", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências da religião", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências do trabalho", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências políticas", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências sanitárias", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências sociais", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cinema", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comércio exterior", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação audiovisual", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicações aeronáuticas", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Construção de Edifícios", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Construção naval", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dança", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho de interiores", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho de moda", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho de produto", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho gráfico", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho industrial", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Design de Interiores", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Economia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação artística", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação física", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação social", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletrônica industrial", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eletrotécnica industrial", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Enfermagem", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia aeronáutica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("ngenharia Agrônoma", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia ambiental", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia cartográfica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia civil", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia da computação", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de alimentos", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de minas", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de produção/industrial", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de telecomunicações", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia elétrica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia eletrônica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia em Montes", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia geológica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia mecânica/mecatrônica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia metalúrgica e de materiais", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia Naval", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia organizacional", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia química", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia técnica agrícola", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia técnica de desenho industrial", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia técnica de obras públicas", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia topográfica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Enologia e viticultura", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Esporte e turismo", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estatística", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estudos internacionais e inter-culturais", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Eventos", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Farmácia e Bioquímica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Filosofia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Física", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fisioterapia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fonoaudiologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fotografia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fotointeligência", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gastronomia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Geografia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Geologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão ambiental", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão de qualidade", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão de Recursos Humanos", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão e administração pública", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão Financeira", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão hospitalar", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão portuária", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Hidrologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("História", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Hotelaria", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Instrumentação e Controle", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Investigação privada", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Jogos digitais", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Jornalismo", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Alemão ", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Árabe", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Espanhol", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Francês", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Inglês", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Italiano", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Línguas e culturas românicas", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Literatura e língua portuguesa", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Lingüística", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Logística", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Marketing", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Matemática", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mecânica de precisão", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Medicina", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Meteorologia e climatologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Náutica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Negócios imobiliários", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Nutrição", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Obstetrícia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Oceanografia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Odontologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Oftálmica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Paisagismo", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Papel e Celulose", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia - Educação secundária", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Petróleo e Gás", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Podologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Polímeros", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Prevenção e segurança do trabalho", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Prevenção e segurança integral", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Processos Gerenciais", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Processos Químicos", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção cultural", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção de cachaça", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção de Cosméticos", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção fonográfica", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção Industrial", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção joalheira", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção moveleira", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção multimídia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção pesqueira", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção sucroalcooleira", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Produção têxtil", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicopedagogia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Publicidade e propaganda", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Química", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Radiologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Refrigeração e Climatização", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Relações Internacionais", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Relações públicas", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Saneamento Ambiental", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Secretariado", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Serviço social", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Silvicultura", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Sistemas de telecomunicações", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Soldagem", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Teatro", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tecnologia da Informação", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Telemática", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Teologia", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Terapia ocupacional", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tradução e interpretação", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Transporte aéreo", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Transporte marítimo", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Turismo", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Veterinária", 5);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Zootécnia", 5);

INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração de empresas", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arqueologia e restauração", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Atendimento preventivo", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências médicas", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dança-Educação", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho do espaço do trabalho", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho e estratégias de comunicação", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho e novos formatos expositivos", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho e produção gráfica", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direção e administração em recursos humanos", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Economia", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharias", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("pecialização em contabilidade e auditoria", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Física", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fonoaudiologia", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão e alimentos", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("História e sociologia", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Hotelaria e Turismo", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Informática", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ligüística, Letras e Artes", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Marketing", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Matemática", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mediação de conflitos", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Melhora ambiental de produtos e processos", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Microeletrônica", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Neuro-psicologia clínica", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Odontologia", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Operações logísticas", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia da educação", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Petroquímica", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pós-graduação desenho e uso em Internet", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicologia clínica infanto-juvenil", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicologia Social", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicomotricidade", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psico-oncologia", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psiquiatria", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Publicidade e Propaganda", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Química", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Reabilitação cognitiva", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Relações Internacionais", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Serviço social", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Técnicas de gestão empresarial", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Terapia sexual e de casal", 6);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Transtornos da linguagem escrita. Dislexia", 6);

INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração de Empresas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração hospitalar", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Análises de sistemas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Animação Telemática/Material Didático virtual", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arquitetura e Urbanismo", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Banco e finanças", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biblioteconomia e documentação", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências biológicas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências Contábeis", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências da Saúde", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências Exatas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências Humanas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências sociais aplicadas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cinematografia", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comércio Exterior", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação audiovisual", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação Social", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cultura e Sociedade", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dança-Educação", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho de interiores", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho gráfico", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho web", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direção administrativo financeira", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direção de TI na empresa", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direção e gestão de centros educativos", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direção e gestão de recursos humanos", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito do meio ambiente", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito do trabalho", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito imobiliário, urbanístico e a edificação", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito Público", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("E-commerce", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Economia empresarial", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia Civil", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia do meio ambiente", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia do software", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia Elétrica/Eletrônica", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia Mecânica", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia Química", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fonoaudiologia", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão ambiental", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão de energias alternativas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão de políticas públicas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Indústria Farmacêutica", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Internet", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ligüística, Letras e Artes", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Marketing", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("MBA (Administração e Direção)", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Medicina", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mestrado em Marketing", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mestrado Microsoft .NET MCAD-2003", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Mestrado profissional meio Oracle 8i-2003", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Música", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Oceanografia", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Odontologia", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Operações logísticas", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia da educação", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Prevenção e Segurança do Trabalho", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Programação JAVA", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Programação Web", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicologia clínica e da saúde", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Química", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tecnologia da informação", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Telecomunicações", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tradução e interpretação", 7);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Turismo", 7);

INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração - Comércio exterior", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração e direção de empresas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração hoteleira", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração - Marketing", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Administração turística", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Agronomia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Antropologia social e cultural", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arqueologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arquitetura e urbanismo", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Arquivologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Auditoria e censura jurada de contas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Aviação comercial. Piloto comercial", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biblioteconomia e documentação", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Biologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Bioquímica", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências ambientais", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências atuariais e financeiras", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências contábeis", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências da computação", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências do trabalho", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências econômicas e empresariais", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências religiosas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências sanitárias", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências sociais e políticas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Ciências sociais e políticas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Cinema", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação audiovisual", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação social - Jornalismo", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação social - Publicidade e propaganda", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Comunicação social - Relações públicas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Dança", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho gráfico", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Desenho industrial", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito ambiental", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Direito internacional", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Economia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação artística - Artes cênicas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação artística - Artes plásticas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação artística - Desenho", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação física", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Educação social", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Enfermagem e obstetrícia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia aeronáutica", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia agronômica", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia ambiental", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia cartográfica", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia civil", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de alimentos", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de computação", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de produção/industrial", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia de telecomunicações", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia elétrica/eletrônica", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia mecânica/mecatrônica", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia organizacional", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia química", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia técnica agrícola", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia técnica de desenho industrial", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Engenharia técnica de obras públicas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Enologia e viticultura", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Esporte e turismo", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estatística", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estudos da Ásia Oriental", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Estudos internacionais e inter-culturais", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Filosofia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Física", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fisioterapia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fonoaudiologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Fotografia e criação digital", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Geografia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Gestão e administração pública", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("História", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("História da arte", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("História e ciências da música", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Indústria farmacêutica", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Investigação privada", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Alemão ", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Árabe", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras clássicas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Espanhol", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Francês", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Inglês", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Italiano", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Línguas e culturas românicas", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Letras - Literatura e língua portuguesa", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Lingüística", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Logística", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Máquinas navais", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Matemática", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Medicina", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Meteorologia e climatologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Náutica e transporte marítimo", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Nutrição humana e dietética", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Oceanografia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Odontologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Outras Engenharias", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Paisagismo", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia - Educação infantil", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia - Educação Música", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia - Educação primária", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia - Educação secundária", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia especial", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Pedagogia - Língua estrangeira", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Piloto de transporte linha aérea", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Prevenção e segurança do trabalho", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Prevenção e segurança integral", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Psicopedagogia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Química", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Recursos Humanos", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Secretariado executivo e bilíngue", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Serviço social", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Sociologia", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Teatro", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tecnologia ambiental", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tecnologia da informação", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Terapia ocupacional", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Tradução e interpretação", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Turismo", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Veterinária", 8);
INSERT INTO curso (curso, nivel_idnivel) VALUES ("Zootécnia", 8);